---
name: "Molecule Test"

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Temporary variable until molecule-docker officially supports ansible 2.19+
env:
  ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"

jobs:
  molecule:
    runs-on: [self-hosted, systemd-runner]
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: kishaningithub/setup-python-amazon-linux@v1
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Install rsync
        run: sudo dnf install -y rsync;

      - name: Lint the role
        run: pipenv run ansible-lint . --exclude=molecule/default/roles

      - name: Run Molecule tests
        run: pipenv run molecule test

  notify_on_failure:
    if: failure()
    needs: [molecule]
    uses: tulibraries/.github/.github/workflows/slack-notify.yml@main
    with:
      repo: ${{ github.repository }}
      run_id: ${{ github.run_id }}
      workflow: ${{ github.workflow }}
    secrets: inherit
